name: arbinex_bottom_bar
description: A customizable Flutter bottom navigation bar with a center action button, notch controls, spacing controls, and multiline label support.
version: 0.1.2
homepage: https://github.com/baxruzismailov/arbinex_bottom_bar
repository: https://github.com/baxruzismailov/arbinex_bottom_bar
issue_tracker: https://github.com/baxruzismailov/arbinex_bottom_bar/issues

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
